# Generated by Django 3.2.6 on 2021-09-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_auto_20210904_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_category',
            old_name='categoryuser',
            new_name='user',
        ),
    ]
